### ISSUE TITLE
The border, title, and content margins, footer offsets, etc should be configurable

### ISSUE THREAD

**Issue by d0c-s4vage** [d0c-s4vage/lookatme#95]
**Describe the Feature Request**

Currently none of the main margins/padding are configurable. Specifically margins/padding for these items should be configurable:

* border
* title
* content
* footer 

**Example Markdown**

```yaml
border:
  padding: 10 10 10 10 # top right bottom left
title:
  align: left | center | right
  padding: 10 10 10 10 # top right bottom left
footer-left:
  padding: 10 10 10 10 # top right bottom left
footer-right:
  padding: 10 10 10 10 # top right bottom left
content:
  padding: 10 10 10 10 # top right bottom left
```

**Screenshot/Wireframe**

**Additional notes**

May need to re-evaluate the top/bottom padding
